### ISSUE TITLE
October 21st, 8AM PST (3PM UTC) community call discussion

### ISSUE THREAD

**Issue by dgkanatsios** [PlayFab/mpscommunity#1]
If you're interested in participating in the Multiplayer Servers community call, please post a reply to this thread with studio and game title name/link as well as any agenda items you would like to be discussed in the call. If you are using the MPS service, feel free to share your experience, we'd love to know more!

- You can join the call by clicking [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTNjZTNhZGYtM2RmNC00MDIzLWI1ZWItZjljM2E2OWUxYjM5%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22cc7c557e-d93a-48c6-af68-a4d6c514d733%22%7d) at the designated date/time
- [Add community call details to your calendar!](https://mpsvarious.blob.core.windows.net/resources/MPS%20Community%20Call.ics)

**Comment by Lisk90** [comment]
Hi everyone! I'm Brent Batas (I go by "Lisk" for game stuff). I've been using PlayFab since ~2016 for my game Legion TD 2, which is out on Steam in Early Access. I've used Multiplayer Servers fairly extensively as well as other PlayFab features such as Entities and Groups. 

My main agenda item I would like to be discussed is recent extended downtimes (where nobody can play our game):

- Oct 5th-6th (10 hours downtime)
- Sept 26-30 (8 hours combined downtime over a few days)
- Sept 14 (8 hours downtime)
- July 15th (1.5 hours)
- July 13th (1.5 hours)

These had to do with Multiplayer Servers as well as Matchmaking (which seems related?). In all cases, we hadn't touched any code on our end, so they were purely downtime with the service.

I've used PlayFab for years and it seems like there has been a significant increase in downtime over the past ~3 months. 

- I'd like to know if others in the community have had the same experience. 
- I'd also like to brainstorm ideas on how developers like me can quickly know if it's "Down for everyone or just me?" because the PlayFab status page usually only gets updated 30-60 minutes after a widespread incident starts happening. It would be really nice if other developers, especially with live titles, can somehow be incentivized to participate in the community Slack channel since often I feel like it goes:

1. Me: anyone else having problems?
2. Radio silence for an hour
3. PlayFab status page is updated

It would be nice if I didn't have to spend that hour panicking/debugging things that didn't need to be debugged. I don't know a good solution yet, but there has to be something better.

**Comment by darvell** [comment]
Hi, I'm Darvell Long and I work on the networking side of Soviet Jump Game https://store.steampowered.com/app/1072710/Soviet_Jump_Game/. My intent in meeting all of you is meeting fellow serious PlayFab users, discussing issues with MPS and finding others who are using the whole system as not intended (e.g. we don't have queues, we always have servers running and pull off some tricks).

My main agenda item would mostly be to hear how people work against the grain of PlayFab, what third party servers other people use and for what purpose and the need for better statistics.

There are definitely issues when dealing with high packet counts most likely due to oversold or overshared resources, how to make this work for the small independent developer is a rough idea I'd like to discuss.

Overall for a community call, I think it would be best to just have all developers there to speak and share our resources, find what's missing and start beginning to share code. For example, we use our own API for rapid matchmaking rather than queue based. Libraries for compressing more data in to player data and more. While this industry mostly being commercial leads to a lack of code sharing, this is hurting PlayFab developers in the long run. I find it harder day by day to justify the cost of MPS especially if other than orchestration, most of the work is being done on my own.

These are vague points but it is hard to point down issues with MPS. Some things are just flaws with PlayFab as a whole, such as having to make excessive amounts of API calls just to validate user data when it could just be a signed JWT with a per-title key that isn't locked to enterprise for example.  I hope to refine some points closer to the date but I am interested in hearing others issues and how much interest there is for genuinely having game studios/developers (be it indie or AAA) work together, open up some of their PlayFab code and further close the cycle of everyone having to privately re-implement the same things.

Hope to speak to you all soon. I have not been working with PlayFab due to other commitments outside of gamedev recently but it's hard to focus down some major points to put on the agenda. I do believe the lack of community collaboration and small things such as the Unity SDK being out of date, a lack of good admin tooling, etc. are big things to bring up.

If this call is private/not recorded (or there are sections for NDA/Privacy), I will be happy to share some private backend code that shows what the standard PlayFab user ends up having to do themselves. I do suggest even for a community event, a basic NDA should be signed by attendees so we are able to discuss things more in depth.

**Comment by dgkanatsios** [comment]
Hey @Lisk90 and @darvell, thanks for taking the time to post your feedback, we really appreciate it! A few points from my side:

@Lisk90, thanks a lot for posting your thoughts! While we’ll discuss your points on the call, allow me to share some information regarding the recent incidents. Since the repo/call is MPS only for the time being, I’ll focus on the related ones. 
-	Regarding the incident on September 14th, we’ve posted an extensive RCA detailing the actions which were taken as we were trying to mitigate the issue as well as our next steps for preventing similar issues in the future. FWIW, during the incident, most MPS APIs were failing, including editing or creation of new builds. However, existing game servers/VMs were not affected and requests for new servers on existing builds were had a variable success rate of 40%-80% during the incident. If your experience was different, we’d be more than happy to chat.
-	The incident on July 2nd was due to a failure to an upstream dependency of Multiplayer Servers hosting service and affected a single region (West Europe). RCA can be found here. 
-	Upstream dependencies were also the reason for the outages on June 4th and June 5th, respective RCAs can be found here and here. Again, these incidents were affecting only specific regions.
Still, we’re very sorry these outages happened. We always strive for “4 9s” availability. As part of that, any incident that causes an outage on a feature triggers alerts on our side with the entire team jumping in to provide a mitigation. Happy to share more and discuss your other thoughts during the call.

@darvell, thanks a lot for your thoughts as well! We would be more than happy to share and document best practices. Also, we’d love to discuss the admin features you’re missing on managing your Builds as well as what you think is missing in the Unity GSDK.

Again, thanks for the great feedback, CU on the call!

**Comment by dgkanatsios** [comment]
thank you all for participating on the first call, CU on the next one!
